@echo off
echo 🧠 Starting WhaleSignalLab Brain Daemon...
start cmd /k "cd /d D:\FruxLabs\WhaleSignalLab && title BrainDaemon && python brain_daemon.py"

echo 🐳 Starting Alpha Agents / Alpha Whales...
wsl bash -l -c "cd /mnt/d/FruxLabs/Alpha-Agents && cargo run -p alpha-whales-bot"
